name = "smoltako-portfolio"
compatibility_date = "2023-12-01"

[site]
bucket = ".next/static"

[build]
command = "npm run build"
cwd = "."
watch_dir = "app"

[env.production]
workers_dev = false
route = "smoltako.space/*"

[env.staging]
workers_dev = true

